import {
	Banknote,
	Landmark,
	Percent,
	HeartHandshake,
	Receipt,
	UserMinus,
	ArrowLeftRight,
	Shuffle,
	Wallet,
	HandCoins,
	User2,
	CreditCard,
	CarFront,
	GraduationCap,
	PersonStanding,
	TrendingUp,
	TrendingDown,
	Layers,
	Ghost,
	Globe,
	AlertCircle,
	Clock,
	Send,
	Zap,
	Utensils,
	ShoppingCart,
	Coffee,
	Wine,
	Key,
	Home,
	Hammer,
	Wifi,
	Lightbulb,
	Droplets,
	Shield,
	Building,
	FileText,
	Fuel,
	Wrench,
	Bus,
	CarTaxiFront,
	Construction,
	Plane,
	Hotel,
	Shirt,
	Smartphone,
	Dog,
	Gift,
	Paperclip,
	Dumbbell,
	Store,
	ShoppingBasket,
	Scissors,
	Cigarette,
	Tag,
	Stethoscope,
	Pill,
	Smile,
	Glasses,
	HeartPulse,
	Sparkles,
	Heart,
	Dices,
	BookOpen,
	Clapperboard,
	Music,
	Gamepad2,
	Ticket,
	ShieldPlus,
	Car,
	Umbrella,
	Baby,
	Laptop,
	Scale,
	Truck,
	Package,
	Cog,
	Gavel,
	HelpCircle,
	Briefcase,
	ShoppingBag,
	ShieldCheck,
	LucideIcon,
} from "lucide-react";

export const ICON_MAP: Record<string, LucideIcon> = {
    // Income
    "Wages": Banknote,
    "Dividends": Landmark,
    "Interest": Percent,
    "Benefits & pension": HeartHandshake,
    "Tax refunds": Receipt,
    "Unemployment": UserMinus,

    // Transfers
    "Account transfers": ArrowLeftRight,
    "Investment transfers": Shuffle,
    "Savings transfers": Wallet,
    "Cash deposits": HandCoins,
    "Cash withdraws": HandCoins,
    "Loans & cash advances": Landmark,
    "Person to person payments": User2,

    // Debt Payments
    "Credit card payments": CreditCard,
    "Auto loan payments": CarFront,
    "Student loan payments": GraduationCap,
    "Personal loan payments": PersonStanding,

    // Investments
    "Buy": TrendingUp,
    "Sell": TrendingDown,
    "ETFs": Layers,
    "Crypto": Ghost,

    // Bank Fees
    "ATM fees": Landmark,
    "Foreign transaction fees": Globe,
    "Insufficient funds": AlertCircle,
    "Interest charge": Percent,
    "Late fees": Clock,
    "Wire fees": Send,
    "Overdraft fees": Zap,

    // Food & Drink
    "Restaurants & bars": Utensils,
    "Groceries": ShoppingCart,
    "Coffee shops": Coffee,
    "Liquor stores": Wine,

    // Housing & Utilities
    "Rent": Key,
    "Mortgage payments": Home,
    "Home improvement & repairs": Hammer,
    "Phone & internet": Wifi,
    "Gas & electricity": Lightbulb,
    "Water sewer & garbage": Droplets,
    "Security": Shield,
    "Hoa fee": Building,
    "Property tax": FileText,

    // Transportation
    "Gasoline & EV charing": Fuel,
    "Car services": Wrench,
    "Public transit": Bus,
    "Taxi & ride shares": CarTaxiFront,
    "Parking & tolls": Construction,

    // Travel
    "Flights": Plane,
    "Hotels": Hotel,
    "Rental cars": Car,

    // Shopping
    "Clothing & accessories": Shirt,
    "Electronics": Smartphone,
    "Pets supplies": Dog,
    "Gifts": Gift,
    "Office supplies": Paperclip,
    "Sports & outdoors": Dumbbell,
    "Retail": Store,
    "Convenience stores": ShoppingBasket,
    "Hair & beauty": Scissors,
    "Tobaco & vape": Cigarette,
    "Other shopping": Tag,

    // Health & Wellness
    "Medical": Stethoscope,
    "Pharmacy": Pill,
    "Dental": Smile,
    "Vision": Glasses,
    "Nursing": HeartPulse,
    "Fitness": Dumbbell,
    "Personal care": Sparkles,
    "Other health & wellness": Heart,

    // Entertainment
    "Gambling": Dices,
    "Book & news": BookOpen,
    "Movies & TV": Clapperboard,
    "Music & audio": Music,
    "Games": Gamepad2,
    "Events & Recreation": Ticket,
    "Other entertainment": Ghost,

    // Insurance
    "Life insurance": Heart,
    "Health insurance": ShieldPlus,
    "Auto insurance": Car,
    "Home insurance": Home,
    "Other insurance": Umbrella,

    // Services
    "Household services": Wrench,
    "Education services": GraduationCap,
    "Veterinary services": Dog,
    "Childcare services": Baby,
    "Digital services": Laptop,
    "Legal services": Scale,
    "Financial services": Landmark,
    "Shipping": Truck,
    "Moving & storage": Package,
    "Other services": Cog,

    // Government & Charity
    "Tax payments": FileText,
    "Government fees": Gavel,
    "Charity": HeartHandshake,
    "Other government & charity": Globe,

    // Other
    "Uncategorized": HelpCircle,

    // Parent Categories
    "Income": TrendingUp,
    "Transfers": ArrowLeftRight,
    "Debt payments": CreditCard,
    "Investments": Briefcase,
    "Bank fees": Landmark,
    "Food & drink": Utensils,
    "Shopping": ShoppingBag,
    "Housing & utilities": Home,
    "Health & wellness": HeartPulse,
    "Entertainment": Gamepad2,
    "Insurance": ShieldCheck,
    "Services": Wrench,
    "Transportation": Car,
    "Travel": Plane,
    "Government & charity": Gavel,
};