import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto_Mono, Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@teispace/next-themes";
import { getTheme } from "@teispace/next-themes/server";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});
const robotoMono = Roboto_Mono({ subsets: ["latin"], variable: "--font-mono" });

export const metadata: Metadata = {
	title: "Finance Tracker",
	description: "Generated by Touch The Sky",
};

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	const initialTheme = await getTheme();

	return (
		<html
			lang="en"
			suppressHydrationWarning
			className={cn("font-sans", inter.variable)}
		>
			<body
				className={`${geistSans.variable} ${geistMono.variable} ${robotoMono.variable} antialiased bg-white dark:bg-black text-gray-900 dark:text-white`}
				suppressHydrationWarning
			>
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					initialTheme={initialTheme ?? undefined}
				>
					<div className="flex flex-col min-h-screen">
						<main className="grow">{children}</main>
					</div>
				</ThemeProvider>
			</body>
		</html>
	);
}
