import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto_Mono, Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/ThemeProvider";
import Script from "next/script";
import { cn } from "@/lib/utils";

const inter = Inter({subsets:['latin'],variable:'--font-sans'});

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
	subsets: ["latin"],
	variable: "--font-mono",
});

export const metadata: Metadata = {
	title: "Finance Tracker",
	description: "Generated by Touch The Sky",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en" suppressHydrationWarning className={cn("font-sans", inter.variable)}>
			{/* ✅ Inject the theme script safely here to avoid React 19 warnings */}
			<head>
				<Script
					id="next-themes-script"
					strategy="beforeInteractive"
					dangerouslySetInnerHTML={{
						__html: `
							(function() {
								try {
									var storedTheme = localStorage.getItem('theme') || 'system';
									var theme = storedTheme === 'system' 
										? (window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light') 
										: storedTheme;
									document.documentElement.classList.remove('light', 'dark');
									document.documentElement.classList.add(theme);
								} catch (e) {}
							})();
						`,
					}}
				/>
			</head>
			<body
				className={`${geistSans.variable} ${geistMono.variable} ${robotoMono.variable} antialiased bg-white dark:bg-black text-gray-900 dark:text-white`}
				suppressHydrationWarning
			>
				{/* ✅ Remove disableTransitionOnChange */}
				<ThemeProvider attribute="class" defaultTheme="system" enableSystem>
					<div className="flex flex-col min-h-screen" suppressHydrationWarning>
						<main className="grow" suppressHydrationWarning>
							{children}
						</main>
					</div>
				</ThemeProvider>
			</body>
		</html>
	);
}
