import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/ThemeProvider";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
	subsets: ["latin"],
	variable: "--font-mono", // Ensure this variable name exists
});

export const metadata: Metadata = {
	title: "Finance Tracker",
	description: "Generated by Touch The Sky",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className="dark" suppressHydrationWarning>
			<body
				className={`${geistSans.variable} ${geistMono.variable} ${robotoMono.variable} antialiased bg-black`}
			>
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange
				>
					<div className="flex flex-col min-h-screen">
						<main className="grow">{children}</main>
					</div>
				</ThemeProvider>
			</body>
		</html>
	);
}
